import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Noto_Sans_Lao } from "next/font/google";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import { ReduxProviders } from "./providers";
import { Toaster } from "@/components/ui/sonner";
const inter = Noto_Sans_Lao({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Smart Menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProviders>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </html>
    </ReduxProviders>

  );
}
